# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import detection_pb2 as detection__pb2


class MlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_unary(
            "/detection.MlService/Process",
            request_serializer=detection__pb2.Query.SerializeToString,
            response_deserializer=detection__pb2.Response.FromString,
        )
        self.FindResult = channel.unary_unary(
            "/detection.MlService/FindResult",
            request_serializer=detection__pb2.ResultReq.SerializeToString,
            response_deserializer=detection__pb2.ResultResp.FromString,
        )


class MlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FindResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Process": grpc.unary_unary_rpc_method_handler(
            servicer.Process,
            request_deserializer=detection__pb2.Query.FromString,
            response_serializer=detection__pb2.Response.SerializeToString,
        ),
        "FindResult": grpc.unary_unary_rpc_method_handler(
            servicer.FindResult,
            request_deserializer=detection__pb2.ResultReq.FromString,
            response_serializer=detection__pb2.ResultResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "detection.MlService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class MlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Process(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/detection.MlService/Process",
            detection__pb2.Query.SerializeToString,
            detection__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def FindResult(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/detection.MlService/FindResult",
            detection__pb2.ResultReq.SerializeToString,
            detection__pb2.ResultResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
