// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: protos/detection.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MlServiceClient is the client API for MlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MlServiceClient interface {
	Process(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Response, error)
	FindResult(ctx context.Context, in *ResultReq, opts ...grpc.CallOption) (*ResultResp, error)
}

type mlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMlServiceClient(cc grpc.ClientConnInterface) MlServiceClient {
	return &mlServiceClient{cc}
}

func (c *mlServiceClient) Process(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/detection.MlService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlServiceClient) FindResult(ctx context.Context, in *ResultReq, opts ...grpc.CallOption) (*ResultResp, error) {
	out := new(ResultResp)
	err := c.cc.Invoke(ctx, "/detection.MlService/FindResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlServiceServer is the server API for MlService service.
// All implementations must embed UnimplementedMlServiceServer
// for forward compatibility
type MlServiceServer interface {
	Process(context.Context, *Query) (*Response, error)
	FindResult(context.Context, *ResultReq) (*ResultResp, error)
	mustEmbedUnimplementedMlServiceServer()
}

// UnimplementedMlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMlServiceServer struct {
}

func (UnimplementedMlServiceServer) Process(context.Context, *Query) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedMlServiceServer) FindResult(context.Context, *ResultReq) (*ResultResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindResult not implemented")
}
func (UnimplementedMlServiceServer) mustEmbedUnimplementedMlServiceServer() {}

// UnsafeMlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MlServiceServer will
// result in compilation errors.
type UnsafeMlServiceServer interface {
	mustEmbedUnimplementedMlServiceServer()
}

func RegisterMlServiceServer(s grpc.ServiceRegistrar, srv MlServiceServer) {
	s.RegisterService(&MlService_ServiceDesc, srv)
}

func _MlService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/detection.MlService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlServiceServer).Process(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlService_FindResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlServiceServer).FindResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/detection.MlService/FindResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlServiceServer).FindResult(ctx, req.(*ResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MlService_ServiceDesc is the grpc.ServiceDesc for MlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detection.MlService",
	HandlerType: (*MlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _MlService_Process_Handler,
		},
		{
			MethodName: "FindResult",
			Handler:    _MlService_FindResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/detection.proto",
}
